version: '3'

services:
  backend:
    container_name: mayk-backend
    build:
      context: ./backend/
    image: 'maykshop'
    depends_on:
      - db
    expose:
      - 6969
    ports:
      - 6969:6969
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/umake
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:16.1-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=umake
