version: '3'

services:
  backend:
    container_name: mayk-backend
    restart: always
    build:
      context: ./backend/
    image: 'maykshop'
    depends_on:
      - db
    expose:
      - ${API_PORT_EXPOSED}
    ports:
      - ${API_PORT_EXPOSED}:${API_PORT}
    environment:
      - SPRING_DATASOURCE_URL=${DB_EXPOSED_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=${API_PORT}

  db:
    image: 'postgres:16.1-alpine'
    container_name: db
    restart: always
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./backend/backup:/backup
